version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "3306:3306"

  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - SECRET_KEY=you-will-never-guess
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/appdb
    depends_on:
      - db
    volumes:
      - .:/app
      - ./templates:/app/templates
      - ./static:/app/static

volumes:
  db-data:
