# Para saber componer las opciones correctamente en TOML en la tecnología Besu se ha utilizado
# en el siguiente enlace:
# https://besu.hyperledger.org/public-networks/reference/cli/options

# Node 1 configuration
min-gas-price=0

# Hecho por mi para la tabla [Node]
data-storage-format="FOREST" # Necesario para privacidad (en posteriores versiones por defecto es "BONSAI")
data-path="/var/lib/besu/QBFT-Network/Node/data" #The path to the Besu data directory. 
#The default is the directory you installed Besu in, or /opt/besu/database if using the Besu Docker image.
p2p-port="30303"
p2p-host="0.0.0.0"

# Hecho por mi para la tabla [RPC]
rpc-http-enabled=true
rpc-http-host="0.0.0.0" #To allow remote connections, set to 0.0.0.0.
rpc-http-port="8545" #The port (TCP) on which HTTP JSON-RPC listens. The default is 8545
# Como por ahora no hemos habilitado autenticación HTTP, eliminamos el acceso a ciertas API
# ADMIN hay que dejar para que Chainlens funcione bien. ¿CAMBIAR de monitorización?
rpc-http-api=["ADMIN","DEBUG","ETH","TXPOOL","NET","TRACE","WEB3","EEA","PLUGINS"]
rpc-http-cors-origins=["all"] # A list of domain URLs for CORS validation. Listed domains can access the node using JSON-RPC. If your client interacts with Besu using a browser app (such as Remix or a block explorer), add the client domain to the list.
# The default value is "none". If you do not list any domains, browser apps cannot interact with your Besu node.
rpc-ws-enabled=true #Enables or disables the WebSocket JSON-RPC service. The default is false
rpc-ws-host="0.0.0.0" #To allow remote connections, set to 0.0.0.0
rpc-ws-port="8546" #The port (TCP) on which WebSocket JSON-RPC listens. The default is 8546
rpc-ws-api=["ADMIN","DEBUG","MINER","ETH","TXPOOL","NET","TRACE","WEB3","EEA","PRIV","PLUGINS","QBFT","PERM"]

# Hecho por mi para la tabla [Network]
network-id="1" # The P2P network identifier.
# Use this option to override the default network ID. The default value is the same 
# as the chain ID defined in the genesis file.

# Hecho por mi para la tabla [Genesis]
genesis-file="/var/lib/besu/QBFT-Network/networkFiles/genesis.json"

# Hecho por mi para la tabla [Metrics]
metrics-enabled=true
 # Enables or disables the metrics exporter. The default is false.
#To enable the Prometheus monitoring and alerting service to access Hyperledger Besu metrics,
#use the --metrics-enabled option.
metrics-host="127.0.0.1" #The host on which Prometheus accesses Besu metrics. The metrics server respects the --host-allowlist option.
#The default is 127.0.0.1.
metrics-port=9545 #The port (TCP) on which Prometheus accesses Besu metrics. The default is 9545. Ports must be exposed appropriately

# Hecho por mi para la tabla [Privacy]
privacy-enabled=true #Enables or disables private transactions. The default is false.
# Esta ultima variable es parte de "Private networks" https://besu.hyperledger.org/private-networks/concepts/privacy#privacy-enabled-networks
#specifies the Q2T server address of the Tessera node (Q2T in tessera.conf)
# El siguiente parámetro como variable de entorno BESU_PRIVACY_URL para mantener este fichero único
#privacy-url=http://tessera_nodeX:9102
# Activamos autenticación solamente para RPC mediante WS por ahora
#rpc-http-authentication-enabled=true
#rpc-http-authentication-jwt-public-key-file="/var/lib/besu/QBFT-Network/networkFiles/TesseraKeys/publicRSAKeyOperator.pem"
rpc-ws-authentication-enabled=true
rpc-ws-authentication-jwt-public-key-file="/var/lib/besu/QBFT-Network/networkFiles/JWTkeys/publicRSAKeyOperator.pem"
privacy-multi-tenancy-enabled=true
# Necesario si activamos privacidad y permisionado de cuentas: POR VARIABLE DE ENTORNO
#privacy-marker-transaction-signing-key-file="/var/lib/besu/QBFT-Network/Node/data/key"

host-allowlist=["*"]

# bootnodes - si estos nodos están en static-nodes.json no hace falta ponerlos aquí.
# bootnodes=[]

# Discovery at boot is set to a list of static files, but will also discover new nodes should they be added
# static nodes
static-nodes-file="/var/lib/besu/QBFT-Network/networkFiles/static-nodes.json"
discovery-enabled=true
permissions-nodes-config-file-enabled=true
permissions-nodes-config-file="/var/lib/besu/QBFT-Network/networkFiles/nodes_permissions_config.toml"
permissions-accounts-config-file-enabled=true
permissions-accounts-config-file="/var/lib/besu/QBFT-Network/networkFiles/accounts_permissions_config.toml"

