version: '3'
services:
  besu-node3:
    image: hyperledger/besu:23.10.2
    hostname: besu_node3
    restart: always
    volumes:
      - .:/var/lib/besu/QBFT-Network
      - ./networkFiles/keys/key3:/var/lib/besu/QBFT-Network/Node/data/key
      - ./networkFiles/keys/key3.pub:/var/lib/besu/QBFT-Network/Node/data/key.pub
    ports:
# RPC_HTTP_PORT:8545
# RPC_WS_PORT:8546
# P2P_PORT:30303
# HTTP_GRAPHQL_PORT:8547
# HTTP_ENGINE_JSON_RPC_PORT:8550
# WS_ENGINE_JSON_RPC_PORT:8551
      - 8545:8545
      - 8546:8546
      - 30303:30303
      - 8547:8547
      - 8550:8550
      - 8551:8551
#    depends_on:
#      - prometheus  
    command: --config-file=/var/lib/besu/QBFT-Network/configNodes/node-config.toml
    environment:
      - BESU_PRIVACY_URL=http://tessera_node3:9102
#      - PATH=/opt/besu/bin:$PATH
#      - JAVA_HOME=/opt/besu/java-19-openjdk-amd64
#      - BESU_VERSION=23.10.1-SNAPSHOT #22.1.0-RC5-SNAPSHOT
#      - NETWORK_ID=1

    networks:
      besu_network:
        ipv4_address: 172.16.0.4

  tessera-node3:
    image: quorumengineering/tessera:23.4.0
    hostname: tessera_node3
    restart: always
    volumes:
      - .:/var/lib/besu/QBFT-Network
      - ./logs/tessera:/var/log/tessera/
      - ./networkFiles/TesseraKeys:/var/lib/besu/QBFT-Network/Node/Tessera
    ports:
      - 9101:9101
      - 9102:9102
      - 9103:9103
    depends_on:
      - besu-node3
    command: --config-file /var/lib/besu/QBFT-Network/Node/Tessera/tessera3.conf
    networks:
      besu_network:

networks:
  besu_network:
    name: besu_network
    driver: overlay
    external: true
