version: '3'
services:
  besu-node2:
    image: hyperledger/besu:23.10.2
    hostname: besu_node2
    restart: always
    volumes:
      - .:/var/lib/besu/QBFT-Network
    ports:
      - 8545:8545 # RPC_HTTP_PORT:8545
      - 8546:8546 # RPC_WS_PORT:8546
      - 30303:30303 # P2P_PORT:30303
      - 8547:8547 # HTTP_GRAPHQL_PORT:8547
      - 8550:8550 # HTTP_ENGINE_JSON_RPC_PORT:8550
      - 8551:8551 # WS_ENGINE_JSON_RPC_PORT:8551
    command: --config-file=/var/lib/besu/QBFT-Network/configNodes/node-config.toml
    environment:
      - BESU_PRIVACY_URL=http://172.16.0.23:9102
      - BESU_NODE_PRIVATE_KEY_FILE=/var/lib/besu/QBFT-Network/networkFiles/keys/key2
      - BESU_PRIVACY_MARKER_TRANSACTION_SIGNING_KEY_FILE=/var/lib/besu/QBFT-Network/networkFiles/keys/key2
    networks:
      besu_network:
        ipv4_address: 172.16.0.3

  tessera-node2:
    image: quorumengineering/tessera:23.4.0
    hostname: tessera_node2
    restart: always
    volumes:
      - .:/var/lib/besu/QBFT-Network
    ports:
      - 9101:9101
      - 9102:9102
      - 9103:9103
    command: --config-file /var/lib/besu/QBFT-Network/configNodes/tessera.conf
    networks:
      besu_network:
        ipv4_address: 172.16.0.23
networks:
  besu_network:
    name: besu_network
    driver: overlay
    external: true
