version: '3'

services:
  ethstats:
    build: ./ethstats-server
    hostname: ethstats
    restart: always
    environment:
      - WS_SECRET=asdf
    ports:
      - "3000:3000"
    networks:
      - server_network
    volumes:
      - ethstats_logs:/app/alertak/logs

  ziurtagiriak:
    build:
      context: ../Pilotoak/ZiurtagiriakAPP
      dockerfile: Dockerfile
    hostname: ziurtagiriak
    restart: always
    #ports:
    #  - "5000:5000"
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - ziurtagiriak.env
    networks:
      - server_network

  etiketa:
    build:
      context: ../Pilotoak/EtiketaAPP
      dockerfile: Dockerfile
    hostname: etiketa
    restart: always
    #ports:
    #  - "5001:5001"
    env_file:
      - etiketa.env
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - server_network

  formakuntza:
    build:
      context: ../Pilotoak/FormakuntzakAPP
      dockerfile: Dockerfile
    hostname: formakuntza
    restart: always
    #ports:
    #  - "5002:5002"
    env_file:
      - formakuntzak.env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - formakuntza_ziurtagiriak:/app/static/certs
    networks:
      - server_network
    
  webserver:
    image: nginx:latest
    hostname: webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - server_network
    volumes:
      - ./nginx/:/etc/nginx/
      - ./nginx/5xx.html:/www/error_pages/5xx.html
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Mount SSL certs (Read Only)
      - /var/www/certbot:/var/www/certbot  # Mount the webroot for Certbot challenges

  mariadb:
    image: mariadb:10.6
    hostname: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: blockchain # CHANGE IT / ALDATU
      #MYSQL_DATABASE: blockchain
      #MYSQL_USER: blockchain
      #MYSQL_PASSWORD: blockchain
    healthcheck:
      test: ["CMD", "/usr/bin/mysql", "-h", "localhost", "-u", "root", "-pblockchain", "-e", "SELECT 1;"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    #ports:
      #- "3306:3306"
    networks:
      - server_network
    volumes:
      - ../Pilotoak/ZiurtagiriakAPP/blockchain-dump.sql:/docker-entrypoint-initdb.d/ziurtagiriak.sql
      - ../Pilotoak/EtiketaAPP/init_db.sql:/docker-entrypoint-initdb.d/etiketa.sql
      - ../Pilotoak/FormakuntzakAPP/init_db.sql:/docker-entrypoint-initdb.d/formakuntzakapp_dump.sql
      - db_data:/var/lib/mysql
      #Nuevos scripts con: docker exec -i mariadb-container mysql -u root -p"your_password" < script.sql

networks:
  server_network:
    name: server_network
    driver: bridge

volumes:
  db_data:
  ethstats_logs:
  formakuntza_ziurtagiriak:
