version: '3'

services:
  ethstats:
    build: ./ethstats-server
    hostname: ethstats
    restart: always
    environment:
      - WS_SECRET=asdf
    ports:
      - "3000:3000"
    networks:
      - server_network
    volumes:
      - ethstats_logs:/app/alertak/logs

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.blockchain.tkn.eus
    restart: always
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      #- "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      #- "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - mail_data:/var/mail/
      - mail_state:/var/mail-state/
      - mail_logs:/var/log/mail/
      - mail_config:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - server_network
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

  ziurtagiriak:
    build:
      context: ../Pilotoak/ZiurtagiriakAPP
      dockerfile: Dockerfile
    hostname: ziurtagiriak
    restart: always
    #ports:
    #  - "5000:5000"
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - ziurtagiriak.env
    networks:
      - server_network

  etiketa:
    build:
      context: ../Pilotoak/EtiketaAPP
      dockerfile: Dockerfile
    hostname: etiketa
    restart: always
    #ports:
    #  - "5001:5001"
    env_file:
      - etiketa.env
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - server_network

  formakuntza:
    build:
      context: ../Pilotoak/FormakuntzakAPP
      dockerfile: Dockerfile
    hostname: formakuntza
    restart: always
    #ports:
    #  - "5002:5002"
    env_file:
      - formakuntzak.env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - formakuntza_ziurtagiriak:/app/static/certs
    networks:
      - server_network
    
  webserver:
    image: nginx:latest
    hostname: webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - server_network
    volumes:
      - ./nginx/:/etc/nginx/
      - ./nginx/5xx.html:/www/error_pages/5xx.html
      - ./nginx/default-page:/var/www/default:ro  # Mount default landing page (Read Only)
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Mount SSL certs (Read Only)
      - /var/www/certbot:/var/www/certbot  # Mount the webroot for Certbot challenges

  mariadb:
    image: mariadb:10.6
    hostname: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: blockchain # CHANGE IT / ALDATU
      #MYSQL_DATABASE: blockchain
      #MYSQL_USER: blockchain
      #MYSQL_PASSWORD: blockchain
    healthcheck:
      test: ["CMD", "/usr/bin/mysql", "-h", "localhost", "-u", "root", "-pblockchain", "-e", "SELECT 1;"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    #ports:
      #- "3306:3306"
    networks:
      - server_network
    volumes:
      - ../Pilotoak/ZiurtagiriakAPP/blockchain-dump.sql:/docker-entrypoint-initdb.d/ziurtagiriak.sql
      - ../Pilotoak/EtiketaAPP/init_db.sql:/docker-entrypoint-initdb.d/etiketa.sql
      - ../Pilotoak/FormakuntzakAPP/init_db.sql:/docker-entrypoint-initdb.d/formakuntzakapp_dump.sql
      - db_data:/var/lib/mysql
      #Nuevos scripts con: docker exec -i mariadb-container mysql -u root -p"your_password" < script.sql

networks:
  server_network:
    name: server_network
    driver: bridge

volumes:
  db_data:
  ethstats_logs:
  formakuntza_ziurtagiriak:
  mail_data:
  mail_state:
  mail_logs:
  mail_config:
