version: '3'

services:
  ziurtagiriak:
    build:
      context: ../Pilotoak/ZiurtagiriakAPP
      dockerfile: Dockerfile
    hostname: ziurtagiriak
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ziurtagiriak.env
    networks:
      - besu_network

  etiketa:
    build:
      context: ../Pilotoak/EtiketaAPP
      dockerfile: Dockerfile
    hostname: etiketa
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - etiketa.env
    depends_on:
      - db
    networks:
      - besu_network

  webserver:
    image: nginx:latest
    hostname: webserver
    restart: always
    ports:
      - "80:80"
    networks:
      - besu_network
    volumes:
      - ./nginx/:/etc/nginx/
      - ./nginx/5xx.html:/www/error_pages/5xx.html

  db:
    image: mariadb:latest
    hostname: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: blockchain
      #MYSQL_DATABASE: blockchain
      #MYSQL_USER: blockchain
      #MYSQL_PASSWORD: blockchain
    ports:
      - "3306:3306"
    networks:
      - besu_network
    volumes:
      - ../Pilotoak/ZiurtagiriakAPP/blockchain-dump.sql:/docker-entrypoint-initdb.d/ziurtagiriak.sql
      - ../Pilotoak/EtiketaAPP/init_db.sql:/docker-entrypoint-initdb.d/etiketa.sql
      - db_data:/var/lib/mysql
      #Nuevos scripts con: docker exec -i mariadb-container mysql -u root -p "your_password" < script.sql

networks:
  besu_network:
    name: besu_network
    driver: overlay
    external: true

volumes:
  db_data:
