version: "3.6"
services:
  api4:
    image: web3labs/epirus-free-api:latest
    restart: always
    hostname: api4
    environment:
      - NODE_ENDPOINT=http://besu_node4:8545
      - MONGO_CLIENT_URI=mongodb://mongodb4:27017
      - REINDEX_ENDPOINT=http://ingestion4/reindex/
      - MONGO_DB_NAME=epirus
      - MONGO_CREATE_INDICES=true
      - REDIS_HOST=redis4
      - REDIS_PORT=6379
    depends_on:
      - redis4 
      - mongodb4
    networks:
      besu_network:
  
  mongodb4:
    image: mongo:5.0.8
    restart: always
    hostname: mongodb4
    environment:
      - COMPOSE_HTTP_TIMEOUT=900
      - DOCKER_CLIENT_TIMEOUT=900
    entrypoint: mongod --bind_ip "0.0.0.0"
    networks:
      besu_network:

  redis4:
    image: redis
    restart: always
    hostname: redis4
    container_name: redis4
    networks:
      besu_network:

  web4:
    image: web3labs/epirus-free-web:latest
    restart: always
    hostname: web4
    environment:
      - API_URL=/api
      - WS_API_URL=ws://besu_node4:8090
      - DISPLAY_NETWORK_TAB=true
    depends_on:
      - api4
    networks:
      besu_network:
  
  ingestion4:
    image: web3labs/epirus-free-ingestion:latest
    restart: always
    hostname: ingestion4
    environment:
      - NODE_ENDPOINT=http://besu_node4:8545
      - MONGO_CLIENT_URI=mongodb://mongodb4:27017
      - MONGO_DB_NAME=epirus
      - NODE_AUTH_BEARER=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJtaXNzaW9ucyI6WyIqOioiXSwicHJpdmFjeVB1YmxpY0tleSI6IjdxSHJ0RG85TVc0UHRPSXgrTkJDWWNqTTNqN0UzaU0rYUExL20rNmpzbnM9In0.ICgnXpZsQJ3R6RK9tFb5Qgyq5X27Qwg_4mVbQVZZteF2cSC7OhfeO_x7FUg1at29G3ifOQmQZFmsnCPDsjVan9GxzzUKgcKsBUNcQ2tgoldOsBzfx9sOxKLZMLHTgNNqXVcc3eX_cpOCxsUKEhrAFNtGIXGx0YR80fdKBT5JZunowQahT8V0JZ6VtnBnqLcoCNwsVx_8X8qb4Tj7PVJLWQL6z7FngZdk27asj5BzGpRdumlhtgmDoBvWldMMocEJp0wjC-mHR5B1dv441SeHfw6doM3yHLeJve3TGW9gPOuronY2DI-CvFuNqohcm_OZ0repfvIQcgoer5Clm4WFeg
    depends_on:
      - mongodb4
    networks:
      besu_network:

  chainlens4:
    image: nginx:latest
    restart: always
    hostname: chainlens4
    volumes:
      - ./nginx4.conf:/etc/nginx/nginx.conf
      - ./5xx.html:/www/error_pages/5xx.html
    ports:
      - 80:80
    depends_on:
      - api4
      - web4
    networks:
      besu_network:
        

networks:
  besu_network:
    name: besu_network
    driver: overlay
    external: true


